### ISSUE TITLE
Black line around the card and more

### ISSUE THREAD

**Issue by calixmagic** [revk/SVG-playing-cards#3]
Hello, is it possible to remove the black line around the cards? My printer ask me to remove it, I have done it manually. 

Other question, is it possible to choose the size of the Jumbo Index. I printed it, but it's to big. A isze between the normal and jumbo could be so cool. The rest of the card can be adapted to the index size like the jumbo option. 

BTW, I'm a magician that want to print my own deck. 

I want to thank you for the job you have done. Thanks a lot. 

Calix

**Comment by revk** [comment]
The print file it generates does not have the black line for this very reason - it has specified bleed area even.
Are you using the code directly or https://www.me.uk/cards/ The "See options for print ready artwork" box adds extra options including 5mm margin, and won't do the black line.

An alternative size would probably be possible. I'll have to look at an option for that.

**Comment by calixmagic** [comment]
Thank you. I don't know why I have this black line in the zip file.

**Comment by revk** [comment]
OK don't use the zip file with svg, click the "email print read PDFs" for print. It will email a PDF with no lines.

The super size is not hard to sort, give me a minute.

**Comment by revk** [comment]
OK I have created a medium size option - it is web site only not in the github here - as it was just tweaks to chosen --vh and --ph options.

**Comment by revk** [comment]
I can see that the "email print ready PDFs" was not working. I have fixed that. Please try that with your design.
