### ISSUE TITLE
Would you be willing to add these two options?

### ISSUE THREAD

**Issue by wdspider** [revk/SVG-playing-cards#4]
I recently stumbled upon your website when looking for a playing card generator. I'm quite impressed at all of the options you currently have. However, the two options I was really hoping for are not there :(

Option 1:  The ability to place the index largely in the center of the card. Similar to the `No court cards images, just large letters` option; but, for all indices.
Option 2:  The ability to have no letter indices (i.e. no A, J, Q, K). Instead, have them 1 through 13 (or 14 if the `Include an 11 pip card` option is checked)

Is there any chance you are still paying attention to this repo and willing to add these options?

**Comment by revk** [comment]
Both look possible, I'll have to look in to it. The first is not that odd, the second seems rather unusual.

**Comment by revk** [comment]
OK, for some reason the git repository is not linked up with my live https://cards.revk.uk/

But try it live for numeric indices now.

**Comment by revk** [comment]
And now there is numeric cards, separately numeric court cards as before, and numeric ace (is set Plain).

**Comment by wdspider** [comment]
Wow, that was quite quick!

Both work as expected. Thanks so much 😊

**Comment by revk** [comment]
Yeh, took a while to tweak the 1's on the 12/13/14/15 as the hight and alignment needed to allow for the curves to look sensible. I think I got it right in the end. Have fun.
